name: Build and Push Release

on:
  workflow_dispatch:
    inputs:
      tagname:
        description: 'Tag name'
        required: true
        default: '0.0.0'

env:
  PUID: '1000'
  PGID: '1000'
  PHP_TZ: 'UTC'

jobs:
  multiarch:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
      -
        name: Login to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          build-args: |
            TARGET=release
          tags: |
            invoiceshelf/invoiceshelf:testing-${{ github.run_id }}

  retag:
    needs: [multiarch]
    runs-on: ubuntu-latest
    container:
      image: gcr.io/go-containerregistry/crane:debug
    steps:
      -
        name: Retag image
        run: |
          crane auth login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} index.docker.io
          crane tag invoiceshelf/invoiceshelf:testing-${{ github.run_id }} ${{ github.event.inputs.tagname }}
          crane tag invoiceshelf/invoiceshelf:testing-${{ github.run_id }} latest
          crane cp invoiceshelf/invoiceshelf:testing-${{ github.run_id }} invoiceshelf/invoiceshelf-laravel:${{ github.event.inputs.tagname }}
          crane tag invoiceshelf/invoiceshelf-laravel:${{ github.event.inputs.tagname }} latest
